services:
  server:
    build:
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    container_name: polar-server
    hostname: polar-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    configs:
      - source: polar_config
        target: /etc/polar/polar.toml
    volumes:
      - cargo-registry:/usr/local/cargo/registry:rw
      - ./../../:/usr/src/app:rw
    depends_on:
      - database
    links:
      - database
    environment:
      POLAR_PROFILE: debug

  database:
    image: postgres:14.2-alpine
    container_name: polar-database
    hostname: polar-database
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: polar
      POSTGRES_USER: polar
      POSTGRES_PASSWORD: polar

configs:
  polar_config:
    file: ./polar.toml

volumes:
  cargo-registry:
  database-data:
