[debug]
address = "0.0.0.0"
port = 8000
ident = "Polar"
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="

[debug.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

#[default.tls]
#certs = "path/to/cert-chain.pem"
#key = "path/to/key.pem"

[debug.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5

[debug.security]
jwt_lifetime = 600
jwt_secret = "secret"

[debug.database]
host = "database"
user = "polar"
password = "polar"
schema = "polar"
