[default]
address = "0.0.0.0"
port = 8000
# workers = 16
# keep_alive = 5
# ident = "Rocket"
# log_level = "normal"
# temp_dir = "/tmp"
# cli_colors = true
[default.security]
jwt_lifetime = 600
jwt_secret = "secret"
[default.database]
host = "127.0.0.1"
user = "polar"
password = "polar"
schema = "polar"
